[phases.setup]
nixPkgs = ['python39', 'pip']

[phases.install]
cmds = ['pip install -r requirements.txt']

[phases.build]
cmds = ['echo "Building Python webhook server"']

[start]
cmd = 'python fub_webhook_server_deploy.py'