name: Run Stage Polling Twice Daily

on:
  schedule:
    - cron: "0 6,18 * * *"  # Runs at 6 AM and 6 PM UTC daily
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests psycopg2-binary

      - name: Run script
        env:
          FUB_API_KEY: ${{ secrets.FUB_API_KEY }}
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          python fub_stage_tracker.py
